# Generated by Django 4.2.8 on 2023-12-25 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Yearly', 'Yearly'), ('Monthly', 'Monthly')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Professional', 'Professional')]),
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
