# Generated by Django 4.2.8 on 2023-12-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_subscription_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
