# Generated by Django 4.2.8 on 2023-12-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
