# Generated by Django 4.2.8 on 2024-01-01 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customuser_otp_customuser_otp_expiry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropDownCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropDownCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.dropdowncategory')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('company_website', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('company_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_industry', to='Users.dropdowncategoryitem')),
                ('company_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_size', to='Users.dropdowncategoryitem')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to='Users.dropdowncategoryitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
